version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - /home/redwan/Desktop/redwan/pdev/programming/python/py3_youtube/web_devs/flask__blog:/counter_app
    links:
      - db:mysql
    container_name: flaskBlog_web_1
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: flaskBlog_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: flaskBlog
